import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Navigation
      'dashboard': 'Dashboard',
      'patients': 'Patients',
      'appointments': 'Appointments',
      'doctors': 'Doctors',
      'admission_counter': 'Admission Counter',
      'billing': 'Billing & Invoices',
      'pharmacy': 'Pharmacy',
      'laboratory': 'Laboratory',
      'opd_management': 'OPD Management',
      'ipd_management': 'IPD Management',
      'icu_management': 'ICU Management',
      'ot_management': 'OT Management',
      'inventory': 'Inventory',
      'pending_tests': 'Pending Tests',
      'completed_tests': 'Completed Tests',
      'resources': 'Resources',
      'prescriptions': 'Prescriptions',
      'medicines': 'Medicines',
      'dispense': 'Dispense',
      'reports': 'Reports',
      'staff': 'Staff Management',
      'settings': 'Settings',
      'profile': 'Profile',
      'logout': 'Logout',

      // Actions & General Buttons
      'save': 'Save',
      'cancel': 'Cancel',
      'close': 'Close',
      'submit': 'Submit',
      'edit': 'Edit',
      'delete': 'Delete',
      'search': 'Search',
      'search_anything': 'Search anything...',
      'filter': 'Filter',
      'refresh': 'Refresh',
      'book_appointment': 'Book Appointment',
      'new_patient': 'New Patient',
      'new_patient_registration': 'New Patient Registration',
      'register_patient': 'Register Patient',
      'help': 'Help',
      'share': 'Share',
      'back': 'Back',
      'notifications': 'Notifications',
      'view': 'View',
      'actions': 'Actions',
      'print': 'Print',
      'download': 'Download',
      'export': 'Export',
      'clear': 'Clear',
      'apply': 'Apply',
      'reset': 'Reset',
      'confirm': 'Confirm',
      'proceed': 'Proceed',
      'select': 'Select',
      'loading': 'Loading...',
      'no_data': 'No data available',
      'all': 'All',
      'date': 'Date',
      'time': 'Time',
      'notes': 'Notes',

      // Theme & Settings
      'app_settings': 'Application Settings',
      'language': 'Language',
      'select_language': 'Select Language',
      'english': 'English',
      'tamil': 'தமிழ் (Tamil)',
      'theme': 'Theme Mode',
      'light_mode': 'Light',
      'dark_mode': 'Dark',
      'system_default': 'System Default',
      'language_subtitle': 'Choose your preferred interface language',
      'theme_subtitle': 'Adjust appearance according to your preference',
      'theme_mode_applied': 'Theme updated successfully',
      'language_applied': 'Language updated successfully',

      // Information & Roles
      'status': 'Status',
      'active': 'Active',
      'inactive': 'Inactive',
      'today': 'Today',
      'welcome': 'Welcome',
      'total_patients': 'Total Patients',
      'upcoming_appointments': 'Upcoming Appointments',
      'recent_patients': 'Recent Patients',
      'staff_id': 'Staff Unique ID',
      'email_address': 'Email Address',
      'mobile_number': 'Mobile Number',
      'onboarded_date': 'Onboarded Date',
      'role': 'Role',
      'admin': 'Administrator',
      'doctor': 'Doctor',
      'nurse': 'Nurse',
      'front_desk': 'Front Desk',
      'lab_technician': 'Lab Technician',
      'pharmacist': 'Pharmacist',

      // Login Screen
      'sign_in_dashboard': 'Sign in to access your dashboard',
      'enter_email_address': 'Enter Email Address',
      'password': 'Password',
      'enter_password': 'Enter Password',
      'forgot_password': 'Forgot Password?',
      'sign_in': 'Sign In',
      'please_enter_email': 'Please enter Email Address',
      'valid_email': 'Please enter a valid email address',
      'please_enter_password': 'Please enter Password',
      'password_min_length': 'Password must be at least 8 characters long',
      'hospital_title': 'Sri Ponni\nMedical Dashboard',
      'hospital_subtitle': 'Secure access for authorized clinical and administrative personnel.',

      // Patient Management
      'patient_records': 'Patients',
      'manage_patient_records': 'Manage patient records and information',
      'search_patients_hint': 'Search patients by name, ID, or phone...',
      'uhid': 'UHID',
      'patient_name': 'Patient Name',
      'age_gender': 'Age / Gender',
      'last_visit': 'Last Visit',
      'all_ages': 'All Ages',
      'all_genders': 'All Genders',
      'all_status': 'All Status',
      'male': 'Male',
      'female': 'Female',
      'other': 'Other',
      'no_patients_found': 'No patients found',

      // Appointments
      'appointment_management': 'Appointments',
      'manage_appointments_subtitle': 'Track and manage doctor consultations',
      'upcoming': 'Upcoming',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'search_appointments_hint': 'Search by patient, doctor, UHID...',
      'date_time': 'Date & Time',
      'slot': 'Slot',
      'select_doctor': 'Select Doctor',
      'select_patient': 'Select Patient',
      'select_date': 'Select Date',
      'no_appointments_found': 'No appointments found',
      'reschedule': 'Reschedule',
      'department': 'Department',
      'type': 'Type',
      'reason': 'Reason',
      'search_appointments': 'Search appointments by patient, doctor, or department...',

      // Doctors
      'doctor_directory': 'Doctors',
      'doctor_directory_subtitle': 'View and manage hospital physicians and specialists',
      'search_doctors_hint': 'Search doctor by name, ID, or specialization...',
      'all_doctors': 'All Doctors',
      'available_today': 'Available Today',
      'on_leave': 'On Leave',
      'specialization': 'Specialization',
      'experience': 'Experience',
      'consultation_fee': 'Consultation Fee',

      // Billing & Invoices
      'billing_invoices': 'Billing & Invoices',
      'manage_billing_subtitle': 'Manage patient billing, invoices, and service catalog',
      'quick_billing': 'Quick Billing',
      'invoices': 'Invoices',
      'generate_invoice': 'Generate Invoice',
      'invoice_no': 'Invoice #',
      'amount': 'Amount',
      'payment_method': 'Payment Method',
      'paid': 'Paid',
      'pending': 'Pending',
      'cash': 'Cash',
      'card': 'Card',
      'upi': 'UPI / Online',
      'subtotal': 'Subtotal',
      'tax': 'Tax',
      'discount': 'Discount',
      'grand_total': 'Grand Total',
      'print_receipt': 'Print Receipt',

      // Pharmacy & Medicines
      'pharmacy_management': 'Pharmacy Management',
      'manage_pharmacy_subtitle': 'Prescriptions, medicine inventory, and dispensing',
      'dispense_medicine': 'Dispense Medicine',
      'medicine_name': 'Medicine Name',
      'dosage': 'Dosage',
      'quantity': 'Quantity',
      'in_stock': 'In Stock',
      'out_of_stock': 'Out of Stock',
      'low_stock': 'Low Stock',

      // Clinical Queues (OPD / IPD / ICU / OT)
      'outpatient_queue': 'OPD Queue',
      'inpatient_queue': 'IPD Patients',
      'bed_number': 'Bed Number',
      'ward': 'Ward',
      'vitals': 'Vitals',
      'blood_pressure': 'Blood Pressure',
      'pulse': 'Pulse',
      'temperature': 'Temperature',
      'spo2': 'SpO2',
      'height': 'Height',
      'weight': 'Weight',
      'admit_patient': 'Admit Patient',
      'discharge': 'Discharge',

      // Dashboards & Stat Cards
      'active_patients': 'Active Patients',
      'today_revenue': "Today's Revenue",
      'active_doctors': 'Active Doctors',
      'quick_actions': 'Quick Actions',
      'recent_activity': 'Recent Activity',
      'system_overview': 'System Overview',
      'pending_vitals': 'Pending Vitals',
      'critical_alerts': 'Critical Alerts',
      'hello': 'Hello',
      'welcome_hospital_overview': "Welcome back! Here's your hospital overview",
      'active_shift': 'Active Shift',
      'general_ward': 'General Ward',
      'assigned_nurse': 'Assigned Nurse',
      'not_assigned': 'Not Assigned',
      'status_assigned': 'Assigned',
      'prev_nurse': 'Prev Nurse',
      'next_nurse': 'Next Nurse',
      'ward_room': 'Ward/Room',
      'none': 'None',
      'view_all': 'View All',
      'view_all_alerts': 'View All Alerts',
      'recent_patients': 'Recent Patients',
      'upcoming_appointments': 'Upcoming Appointments',
      'no_patients_found': 'No patients found',
      'no_appointments_today': 'No appointments for today',
      'registered': 'Registered',
      'quick': 'Quick',
      'standard': 'Standard',
      'total_patients': 'Total Patients',
      'today_appointments': "Today's Appointments",
      'active_admissions': 'Active Admissions',
      'patient_visits': 'Patient Visits',
      'pending_shift_handover': 'Pending Shift Handover',
      'acknowledge': 'Acknowledge',
      'alert_opd_inflow': 'High Patient Inflow in OPD',
      'alert_ward_capacity': 'Ward A Approaching Capacity',
      'years_short': 'y',
      'gender_male': 'Male',
      'gender_female': 'Female',
      'leave_page': 'Leave Page',
      'stay_on_page': 'Stay on Page',
      'unsaved_clinical_data': 'Unsaved Clinical Session Data',
      'unsaved_patient_reg': 'Unsaved Patient Registration',

      // Patient Registration & Clinical Workflow
      'complete': 'Complete',
      'home_visit_care': 'Home Visit Care',
      'home_visit_care_services': 'Home Visit Care & Services',
      'schedule_home_visit': 'Schedule Home Visit',
      'manage_home_visit_desc': 'Manage patient home care, vitals, dressing & attender billing',
      'home_visit_timeline': 'Home Visit Timeline',
      'no_home_visit_records': 'No Home Visit Records Found',
      'no_home_visit_desc': 'There are no home visits recorded for this patient.',
      'total_visits': 'Total Visits',
      'scheduled': 'Scheduled',
      'in_progress': 'In-Progress',
      'completed_status': 'Completed',
      'cancelled': 'Cancelled',
      'total': 'Total',
      'active': 'Active',
      'all': 'All',
      'all_dates': 'All Dates',
      'today': 'Today',
      'tomorrow': 'Tomorrow',
      'pick_date': 'Pick Date',
      'search_patient_hint': 'Search patient, patient ID, visit #...',
      'search_patient_admin_hint': 'Search patient, patient ID, nurse, visit #...',
      'no_home_visits_found': 'No home visits found matching search or filter.',
      'view_summary': 'View Summary',
      'execute_visit': 'Execute Visit',
      'resume_visit': 'Resume Visit',
      'stop_care_plan': 'Stop Care Plan',
      'patient_label': 'Patient:',
      'tab_kit_devices': 'Kit & Devices',
      'tab_vitals': 'Vitals',
      'tab_nursing_care': 'Nursing Care & Dressing',
      'tab_meds_consumables': 'Meds & Consumables',
      'tab_photo_evidence': 'Photo Evidence',
      'tab_live_summary': 'View Live Summary',
      'select_add_kit_header': 'Select & Add Kit Items & Medical Devices Used',
      'select_add_kit_sub': 'Add the kit items or medical devices used during this visit.',
      'add_kit_box_header': 'Add Kit Device / Item Used During Visit',
      'kit_device_item': 'Kit / Device Item',
      'select_kit_item_hint': 'Select Kit Item / Device',
      'category': 'Category',
      'quantity': 'Quantity',
      'add_kit_item': 'Add Kit Item',
      'adding': 'Adding...',
      'carried_used_kit_list': 'Carried & Used Kit Devices List',
      'items': 'Items',
      'qty': 'Qty',
      'unsaved_form_data': 'Unsaved Form Data',
      'unsaved_form_leave_confirm': 'Do you want to leave this page? Any unsaved form data or entries will be lost.',
      'leave_page': 'Leave Page',
      'stay_on_page': 'Stay on Page',
      'home_visit_care': 'Home Visit Care',
      'stop_discontinue_care': 'Stop / Discontinue Care',
      'visit_num_label': 'Visit #:',
      'date_label': 'Date:',
      'back_to_patients': 'Back to Patients',
      'complete_patient_profile': 'Complete Patient Profile',
      'edit_patient_profile': 'Edit Patient Profile',
      'fill_patient_info_history': 'Fill in patient information and medical history',
      'update_patient_info_history': 'Update patient information and medical history',
      'basic_details': 'Basic Details',
      'medical_intake': 'Medical Intake',
      'lifestyle_data': 'Lifestyle Data',
      'review': 'Review',
      'full_name': 'Full Name',
      'enter_patient_full_name': "Enter patient's full name",
      'date_of_birth': 'Date of Birth',
      'gender': 'Gender',
      'select_gender': 'Select gender',
      'mobile_number': 'Mobile Number',
      'enter_mobile_number': 'Enter Mobile Number',
      'emergency_contact_name': 'Emergency Contact Name',
      'enter_name': 'Enter name',
      'relation': 'Relation',
      'enter_relation': 'Enter Relationship',
      'emergency_mobile_number': 'Emergency Mobile Number',
      'address_line_1': 'Address Line 1',
      'enter_address_line_1': 'Enter Address Line 1',
      'address_line_2': 'Address Line 2',
      'enter_address_line_2': 'Enter Address Line 2',
      'district': 'District',
      'select_district': 'Select district',
      'pincode': 'Pincode',
      'enter_pincode': 'Enter Pincode',
      'next': 'Next',
      'prev': 'Previous',
      'height_cm': 'Height (cm)',
      'weight_kg': 'Weight (kg)',
      'bp_systolic': 'BP Systolic (mmHg)',
      'bp_diastolic': 'BP Diastolic (mmHg)',
      'sugar_level': 'Sugar Level (mg/dL)',
      'temperature_f': 'Temperature (°F)',
      'blood_group': 'Blood Group',
      'select_blood_group': 'Select blood group',
      'allergies': 'Allergies',
      'chronic_conditions': 'Chronic Conditions',
      'reason_for_visit': 'Reason for Visit',
      'past_medical_history': 'Past Medical History',
      'smoking_status': 'Smoking Status',
      'alcohol_status': 'Alcohol Status',
      'occupation': 'Occupation',
      'hobbies': 'Hobbies',
      'food_habits': 'Food Habits',
      'physical_activity': 'Physical Activity',
      'quick_register': 'Quick Register',
      'standard_register': 'Standard Register',

      // Password Recovery
      'forgot_password_title': 'Forgot Password',
      'forgot_password_subtitle': 'Enter your registered email address to receive a verification OTP.',
      'send_otp': 'Send Verification Code',
      'enter_otp': 'Enter Verification Code',
      'resend_otp': 'Resend Code',
      'verify_otp': 'Verify & Proceed',
      'new_password': 'New Password',
      'confirm_password': 'Confirm New Password',
      'reset_password': 'Reset Password',
      'back_to_sign_in': 'Back to Sign In',
      'password_reset_success': 'Password has been reset successfully!',
    },
    'ta': {
      // Navigation
      'dashboard': 'முகப்பு',
      'patients': 'நோயாளிகள்',
      'appointments': 'முன்பதிவுகள்',
      'doctors': 'மருத்துவர்கள்',
      'admission_counter': 'சேர்க்கை பிரிவு',
      'billing': 'கட்டணம் & ரசீதுகள்',
      'pharmacy': 'மருந்தகம்',
      'laboratory': 'ஆய்வகம்',
      'opd_management': 'வெளிநோயாளி பிரிவு',
      'ipd_management': 'உள்நோயாளி பிரிவு',
      'icu_management': 'தீவிர சிகிச்சை பிரிவு',
      'ot_management': 'அறுவை சிகிச்சை அரங்கம்',
      'inventory': 'இருப்பு மேலாண்மை',
      'pending_tests': 'நிலுவை சோதனைகள்',
      'completed_tests': 'முடிந்த சோதனைகள்',
      'resources': 'வளங்கள்',
      'prescriptions': 'மருந்துச் சீட்டுகள்',
      'medicines': 'மருந்துகள்',
      'dispense': 'மருந்து வழங்குதல்',
      'reports': 'அறிக்கைகள்',
      'staff': 'பணியாளர்கள் மேலாண்மை',
      'settings': 'அமைப்புகள்',
      'profile': 'சுயவிவரம்',
      'logout': 'வெளியேறு',

      // Actions & General Buttons
      'save': 'சேமி',
      'cancel': 'ரத்து செய்',
      'close': 'மூடு',
      'submit': 'சமர்ப்பி',
      'edit': 'திருத்து',
      'delete': 'நீக்கு',
      'search': 'தேடுக',
      'search_anything': 'தேடவும்...',
      'filter': 'வடிகட்டு',
      'refresh': 'புதுப்பி',
      'book_appointment': 'முன்பதிவு செய்க',
      'new_patient': 'புதிய நோயாளி',
      'new_patient_registration': 'புதிய நோயாளி பதிவு',
      'register_patient': 'நோயாளி பதிவு செய்',
      'help': 'உதவி',
      'share': 'பகிர்',
      'back': 'பின்னே',
      'notifications': 'அறிவிப்புகள்',
      'view': 'காண்க',
      'actions': 'செயல்கள்',
      'print': 'அச்சிடு',
      'download': 'பதிவிறக்கு',
      'export': 'ஏற்றுமதி',
      'clear': 'அழி',
      'apply': 'பயன்படுத்து',
      'reset': 'மீட்டமை',
      'confirm': 'உறுதிப்படுத்து',
      'proceed': 'தொடரவும்',
      'select': 'தேர்ந்தெடு',
      'loading': 'ஏற்றுகிறது...',
      'no_data': 'தகவல் எதுவும் இல்லை',
      'all': 'அனைத்தும்',
      'date': 'தேதி',
      'time': 'நேரம்',
      'notes': 'குறிப்புகள்',

      // Theme & Settings
      'app_settings': 'பயன்பாட்டு அமைப்புகள்',
      'language': 'மொழி',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'english': 'English (ஆங்கிலம்)',
      'tamil': 'தமிழ் (Tamil)',
      'theme': 'தீம் பயன்முறை',
      'light_mode': 'வெளிச்சம் (Light)',
      'dark_mode': 'இருள் (Dark)',
      'system_default': 'கணினி இயல்பு (System)',
      'language_subtitle': 'பயன்பாட்டின் மொழியைத் தேர்ந்தெடுக்கவும்',
      'theme_subtitle': 'உங்கள் விருப்பத்திற்கேற்ப தோற்றத்தை மாற்றவும்',
      'theme_mode_applied': 'தீம் வெற்றிகரமாக மாற்றப்பட்டது',
      'language_applied': 'மொழி வெற்றிகரமாக மாற்றப்பட்டது',

      // Information & Roles
      'status': 'நிலை',
      'active': 'செயலில்',
      'inactive': 'செயலற்றது',
      'today': 'இன்று',
      'welcome': 'வரவேற்கிறோம்',
      'total_patients': 'மொத்த நோயாளிகள்',
      'upcoming_appointments': 'வரவிருக்கும் முன்பதிவுகள்',
      'recent_patients': 'சமீபத்திய நோயாளிகள்',
      'staff_id': 'பணியாளர் எண்',
      'email_address': 'மின்னஞ்சல் முகவரி',
      'mobile_number': 'அலைபேசி எண்',
      'onboarded_date': 'சேர்ந்த தேதி',
      'role': 'பதவி',
      'admin': 'நிர்வாகி',
      'doctor': 'மருத்துவர்',
      'nurse': 'செவிலியர்',
      'front_desk': 'வரவேற்பாளர்',
      'lab_technician': 'ஆய்வக வல்லுநர்',
      'pharmacist': 'மருந்தாளர்',

      // Login Screen
      'sign_in_dashboard': 'உங்கள் முகப்பை அணுக உள்நுழையவும்',
      'enter_email_address': 'மின்னஞ்சல் முகவரியை உள்ளிடவும்',
      'password': 'கடவுச்சொல்',
      'enter_password': 'கடவுச்சொல்லை உள்ளிடவும்',
      'forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
      'sign_in': 'உள்நுழைக',
      'please_enter_email': 'மின்னஞ்சல் முகவரியை உள்ளிடவும்',
      'valid_email': 'சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்',
      'please_enter_password': 'கடவுச்சொல்லை உள்ளிடவும்',
      'password_min_length': 'கடவுச்சொல் குறைந்தபட்சம் 8 எழுத்துக்கள் இருக்க வேண்டும்',
      'hospital_title': 'ஸ்ரீ பொன்னி\nமருத்துவ முகப்பு',
      'hospital_subtitle': 'அங்கீகரிக்கப்பட்ட மருத்துவம் மற்றும் நிர்வாகப் பணியாளர்களுக்கான பாதுகாப்பான தளம்.',

      // Patient Management
      'patient_records': 'நோயாளிகள்',
      'manage_patient_records': 'நோயாளி பதிவுகள் மற்றும் தகவல்களை நிர்வகிக்கவும்',
      'search_patients_hint': 'பெயர், எண் அல்லது அலைபேசி மூலம் தேடவும்...',
      'uhid': 'நோயாளி எண் (UHID)',
      'patient_name': 'நோயாளி பெயர்',
      'age_gender': 'வயது / பாலினம்',
      'last_visit': 'கடைசி வருகை',
      'all_ages': 'அனைத்து வயது',
      'all_genders': 'அனைத்து பாலினம்',
      'all_status': 'அனைத்து நிலை',
      'male': 'ஆண்',
      'female': 'பெண்',
      'other': 'மற்றவை',
      'no_patients_found': 'நோயாளிகள் எவரும் காணப்படவில்லை',

      // Appointments
      'appointment_management': 'முன்பதிவுகள்',
      'manage_appointments_subtitle': 'மருத்துவர் ஆலோசனைகளை கண்காணித்து நிர்வகிக்கவும்',
      'upcoming': 'வரவிருக்கும்',
      'completed': 'முடிந்தவை',
      'cancelled': 'ரத்து செய்யப்பட்டவை',
      'search_appointments_hint': 'நோயாளி, மருத்துவர் அல்லது UHID மூலம் தேடுக...',
      'date_time': 'தேதி & நேரம்',
      'slot': 'நேர இடைவெளி',
      'select_doctor': 'மருத்துவரைத் தேர்ந்தெடுக்கவும்',
      'select_patient': 'நோயாளியைத் தேர்ந்தெடுக்கவும்',
      'select_date': 'தேதியைத் தேர்ந்தெடுக்கவும்',
      'no_appointments_found': 'முன்பதிவுகள் எதுவும் இல்லை',
      'reschedule': 'நேரம் மாற்று',
      'department': 'துறை',
      'type': 'வகை',
      'reason': 'காரணம்',
      'search_appointments': 'நோயாளி, மருத்துவர் அல்லது துறை மூலம் தேடுக...',

      // Doctors
      'doctor_directory': 'மருத்துவர்கள்',
      'doctor_directory_subtitle': 'மருத்துவமனை மருத்துவர்கள் மற்றும் நிபுணர்களைக் காண்க',
      'search_doctors_hint': 'பெயர், எண் அல்லது சிறப்புத் துறை மூலம் தேடுக...',
      'all_doctors': 'அனைத்து மருத்துவர்கள்',
      'available_today': 'இன்று கிடைக்கும் மருத்துவர்கள்',
      'on_leave': 'விடுப்பில்',
      'specialization': 'சிறப்புத் துறை',
      'experience': 'அனுபவம்',
      'consultation_fee': 'ஆலோசனைக் கட்டணம்',

      // Billing & Invoices
      'billing_invoices': 'கட்டணம் & ரசீதுகள்',
      'manage_billing_subtitle': 'கட்டணங்கள், ரசீதுகள் மற்றும் சேவைகளை நிர்வகிக்கவும்',
      'quick_billing': 'விரைவு கட்டணம்',
      'invoices': 'ரசீதுகள்',
      'generate_invoice': 'ரசீது உருவாக்கு',
      'invoice_no': 'ரசீது எண்',
      'amount': 'தொகை',
      'payment_method': 'பணம் செலுத்தும் முறை',
      'paid': 'செலுத்தப்பட்டது',
      'pending': 'நிலுவையில்',
      'cash': 'ரொக்கம்',
      'card': 'அட்டை (Card)',
      'upi': 'UPI / இணைய வழி',
      'subtotal': 'கூட்டுத் தொகை',
      'tax': 'வரி',
      'discount': 'தள்ளுபடி',
      'grand_total': 'மொத்தத் தொகை',
      'print_receipt': 'ரசீது அச்சிடு',

      // Pharmacy & Medicines
      'pharmacy_management': 'மருந்தக மேலாண்மை',
      'manage_pharmacy_subtitle': 'மருந்துச் சீட்டுகள், மருந்துகள் இருப்பு மற்றும் வழங்கல்',
      'dispense_medicine': 'மருந்து வழங்கு',
      'medicine_name': 'மருந்தின் பெயர்',
      'dosage': 'அளவு',
      'quantity': 'எண்ணிக்கை',
      'in_stock': 'இருப்பில் உள்ளது',
      'out_of_stock': 'இருப்பில் இல்லை',
      'low_stock': 'குறைந்த இருப்பு',

      // Clinical Queues (OPD / IPD / ICU / OT)
      'outpatient_queue': 'வெளிநோயாளி வரிசை',
      'inpatient_queue': 'உள்நோயாளிகள்',
      'bed_number': 'படுக்கை எண்',
      'ward': 'வார்டு',
      'vitals': 'முக்கிய அறிகுறிகள்',
      'blood_pressure': 'இரத்த அழுத்தம்',
      'pulse': 'நாடித் துடிப்பு',
      'temperature': 'உடல் வெப்பநிலை',
      'spo2': 'இரத்த ஆக்ஸிஜன் (SpO2)',
      'height': 'உயரம்',
      'weight': 'எடை',
      'admit_patient': 'சேர்க்கை செய்க',
      'discharge': 'வெளியேற்றுதல்',

      // Dashboards & Stat Cards
      'active_patients': 'செயலில் உள்ள நோயாளிகள்',
      'today_revenue': 'இன்றைய வருவாய்',
      'active_doctors': 'செயலில் உள்ள மருத்துவர்கள்',
      'quick_actions': 'விரைவு செயல்கள்',
      'recent_activity': 'சமீபத்திய நிகழ்வுகள்',
      'system_overview': 'அமைப்பின் கண்ணோட்டம்',
      'pending_vitals': 'நிலுவை முக்கிய அறிகுறிகள்',
      'critical_alerts': 'முக்கிய எச்சரிக்கைகள்',
      'hello': 'வணக்கம்',
      'welcome_hospital_overview': 'மீண்டும் வருக! உங்கள் மருத்துவமனை கண்ணோட்டம்',
      'active_shift': 'செயலில் உள்ள ஷிப்ட்',
      'general_ward': 'பொது வார்டு',
      'assigned_nurse': 'நியமிக்கப்பட்ட செவிலியர்',
      'not_assigned': 'நியமிக்கப்படவில்லை',
      'status_assigned': 'நியமிக்கப்பட்டது',
      'prev_nurse': 'முந்தைய செவிலியர்',
      'next_nurse': 'அடுத்த செவிலியர்',
      'ward_room': 'வார்டு/அறை',
      'none': 'எதுவுமில்லை',
      'view_all': 'அனைத்தையும் காண்க',
      'view_all_alerts': 'அனைத்து எச்சரிக்கைகளையும் காண்க',
      'recent_patients': 'சமீபத்திய நோயாளிகள்',
      'upcoming_appointments': 'வரவிருக்கும் முன்பதிவுகள்',
      'no_patients_found': 'நோயாளிகள் யாரும் இல்லை',
      'no_appointments_today': 'இன்று முன்பதிவுகள் ஏதுமில்லை',
      'registered': 'பதிவு செய்யப்பட்டது',
      'quick': 'விரைவு',
      'standard': 'நிலையானது',
      'total_patients': 'மொத்த நோயாளிகள்',
      'today_appointments': 'இன்றைய முன்பதிவுகள்',
      'active_admissions': 'உள்நோயாளிகள் சேர்க்கை',
      'patient_visits': 'நோயாளி வருகைகள்',
      'pending_shift_handover': 'ஷிப்ட் ஒப்படைப்பு நிலுவையில் உள்ளது',
      'acknowledge': 'ஏற்றுக்கொள்',
      'alert_opd_inflow': 'OPD-யில் நோயாளிகளின் அதிக வருகை',
      'alert_ward_capacity': 'வார்டு A முழுமை நிலையை எட்டுகிறது',
      'years_short': 'ஆ',
      'gender_male': 'ஆண்',
      'gender_female': 'பெண்',
      'leave_page': 'வெளியேறு',
      'stay_on_page': 'பக்கத்தில் இரு',
      'unsaved_clinical_data': 'சேமிக்கப்படாத மருத்துவ அமர்வு தரவு',
      'unsaved_patient_reg': 'சேமிக்கப்படாத நோயாளி பதிவு',

      // Patient Registration & Clinical Workflow
      'complete': 'முடிக்கவும்',
      'home_visit_care': 'வீட்டுப் பராமரிப்பு சேவை',
      'home_visit_care_services': 'வீட்டுப் பராமரிப்பு சேவைகள்',
      'schedule_home_visit': 'வீட்டுப் பராமரிப்பை திட்டமிடு',
      'manage_home_visit_desc': 'நோயாளியின் வீட்டு பராமரிப்பு, முக்கிய அளவீடுகள், டிரஸ்ஸிங் மற்றும் பில்லிங் நிர்வகிக்கவும்',
      'home_visit_timeline': 'வீட்டுப் பராமரிப்பு காலவரிசை',
      'no_home_visit_records': 'வீட்டுப் பராமரிப்பு பதிவுகள் எதுவும் இல்லை',
      'no_home_visit_desc': 'இந்த நோயாளிக்கு வீட்டுப் பராமரிப்பு பதிவுகள் எதுவும் இல்லை.',
      'total_visits': 'மொத்த வருகைகள்',
      'scheduled': 'திட்டமிடப்பட்டவை',
      'in_progress': 'செயலில் உள்ளவை',
      'completed_status': 'முடிந்தவை',
      'cancelled': 'ரத்து செய்யப்பட்டவை',
      'total': 'மொத்தம்',
      'active': 'செயலில்',
      'all': 'அனைத்தும்',
      'all_dates': 'அனைத்து தேதிகள்',
      'today': 'இன்று',
      'tomorrow': 'நாளை',
      'pick_date': 'தேதியைத் தேர்ந்தெடு',
      'search_patient_hint': 'நோயாளி, நோயாளி ஐடி, வருகை # தேடவும்...',
      'search_patient_admin_hint': 'நோயாளி, நோயாளி ஐடி, செவிலியர், வருகை # தேடவும்...',
      'no_home_visits_found': 'தேடலுக்குப் பொருந்தக்கூடிய வீட்டுப் பராமரிப்பு வருகைகள் எதுவும் கிடைக்கவில்லை.',
      'view_summary': 'சுருக்கத்தைப் பார்க்கவும்',
      'execute_visit': 'வருகையை செயல்படுத்தவும்',
      'resume_visit': 'வருகையைத் தொடரவும்',
      'stop_care_plan': 'பராமரிப்புத் திட்டத்தை நிறுத்து',
      'patient_label': 'நோயாளி:',
      'tab_kit_devices': 'கிட் மற்றும் உபகரணங்கள்',
      'tab_vitals': 'முக்கிய அளவீடுகள் (Vitals)',
      'tab_nursing_care': 'செவிலியர் பராமரிப்பு மற்றும் டிரஸ்ஸிங்',
      'tab_meds_consumables': 'மருந்துகள் மற்றும் உபயோகப் பொருட்கள்',
      'tab_photo_evidence': 'புகைப்பட ஆதாரம்',
      'tab_live_summary': 'நேரடி சுருக்கத்தைப் பார்க்கவும்',
      'select_add_kit_header': 'பயன்படுத்திய கிட் பொருட்கள் மற்றும் மருத்துவ உபகரணங்களைத் தேர்ந்தெடுக்கவும்',
      'select_add_kit_sub': 'இந்த வருகையின் போது பயன்படுத்தப்பட்ட கிட் பொருட்கள் அல்லது மருத்துவ உபகரணங்களைச் சேர்க்கவும்.',
      'add_kit_box_header': 'வருகையின் போது பயன்படுத்திய கிட் கருவி / பொருளைச் சேர்க்கவும்',
      'kit_device_item': 'கிட் / கருவி உருப்படி',
      'select_kit_item_hint': 'கிட் பொருள் / கருவியைத் தேர்ந்தெடுக்கவும்',
      'category': 'வகை',
      'quantity': 'அளவு',
      'add_kit_item': '+ கிட் பொருளைச் சேர்',
      'adding': 'சேர்க்கிறது...',
      'carried_used_kit_list': 'கொண்டுவரப்பட்ட மற்றும் பயன்படுத்தப்பட்ட கிட் கருவிகளின் பட்டியல்',
      'items': 'உருப்படிகள்',
      'qty': 'அளவு',
      'unsaved_form_data': 'சேமிக்கப்படாத படிவத் தரவு',
      'unsaved_form_leave_confirm': 'இந்தப் பக்கத்தை விட்டு வெளியேற விரும்புகிறீர்களா? சேமிக்கப்படாத படிவத் தரவு அல்லது உள்ளீடுகள் இழக்கப்படும்.',
      'leave_page': 'வெளியேறு',
      'stay_on_page': 'இப்பக்கத்திலேயே இரு',
      'home_visit_care': 'வீட்டுப் பராமரிப்பு சேவை',
      'stop_discontinue_care': 'பராமரிப்பை நிறுத்து',
      'visit_num_label': 'வருகை #:',
      'date_label': 'தேதி:',
      'back_to_patients': 'நோயாளிகள் பட்டியலுக்குத் திரும்பு',
      'complete_patient_profile': 'நோயாளி சுயவிவரத்தை முடிக்கவும்',
      'edit_patient_profile': 'நோயாளி சுயவிவரத்தைத் திருத்து',
      'fill_patient_info_history': 'நோயாளி தகவல் மற்றும் மருத்துவ வரலாற்றை நிரப்பவும்',
      'update_patient_info_history': 'நோயாளி தகவல் மற்றும் மருத்துவ வரலாற்றைப் புதுப்பிக்கவும்',
      'basic_details': 'அடிப்படை விவரங்கள்',
      'medical_intake': 'மருத்துவ விவரங்கள்',
      'lifestyle_data': 'வாழ்க்கை முறை தரவு',
      'review': 'சரிபார்த்தல்',
      'full_name': 'முழு பெயர்',
      'enter_patient_full_name': 'நோயாளியின் முழு பெயரை உள்ளிடவும்',
      'date_of_birth': 'பிறந்த தேதி',
      'gender': 'பாலினம்',
      'select_gender': 'பாலினத்தைத் தேர்ந்தெடுக்கவும்',
      'mobile_number': 'கைப்பேசி எண்',
      'enter_mobile_number': 'கைப்பேசி எண்ணை உள்ளிடவும்',
      'emergency_contact_name': 'அவசர தொடர்பு பெயர்',
      'enter_name': 'பெயரை உள்ளிடவும்',
      'relation': 'உறவுமுறை',
      'enter_relation': 'உறவுமுறையை உள்ளிடவும்',
      'emergency_mobile_number': 'அவசர தொடர்பு கைப்பேசி எண்',
      'address_line_1': 'முகவரி வரி 1',
      'enter_address_line_1': 'முகவரி வரி 1-ஐ உள்ளிடவும்',
      'address_line_2': 'முகவரி வரி 2',
      'enter_address_line_2': 'முகவரி வரி 2-ஐ உள்ளிடவும்',
      'district': 'மாவட்டம்',
      'select_district': 'மாவட்டத்தைத் தேர்ந்தெடுக்கவும்',
      'pincode': 'அஞ்சல் குறியீடு',
      'enter_pincode': 'அஞ்சல் குறியீட்டை உள்ளிடவும்',
      'next': 'அடுத்து',
      'prev': 'முந்தையது',
      'height_cm': 'உயரம் (செ.மீ)',
      'weight_kg': 'எடை (கிலோ)',
      'bp_systolic': 'இரத்த அழுத்தம் சிஸ்டாலிக் (mmHg)',
      'bp_diastolic': 'இரத்த அழுத்தம் டயஸ்டாலிக் (mmHg)',
      'sugar_level': 'சர்க்கரை அளவு (mg/dL)',
      'temperature_f': 'உடல் வெப்பநிலை (°F)',
      'blood_group': 'இரத்த வகை',
      'select_blood_group': 'இரத்த வகையைத் தேர்ந்தெடுக்கவும்',
      'allergies': 'ஒவ்வாமைகள் (Allergies)',
      'chronic_conditions': 'நீண்டகால நோய்கள் (Chronic Conditions)',
      'reason_for_visit': 'வருகைக்கான காரணம்',
      'past_medical_history': 'முந்தைய மருத்துவ வரலாறு',
      'smoking_status': 'புகைபிடிக்கும் பழக்கம்',
      'alcohol_status': 'மது அருந்தும் பழக்கம்',
      'occupation': 'தொழில்',
      'hobbies': 'பொழுதுபோக்குகள்',
      'food_habits': 'உணவுப் பழக்கம்',
      'physical_activity': 'உடற்பயிற்சி / செயல்பாடு',
      'quick_register': 'விரைவு பதிவு',
      'standard_register': 'வழக்கமான பதிவு',

      // Password Recovery
      'forgot_password_title': 'கடவுச்சொல் மறந்துவிட்டதா?',
      'forgot_password_subtitle': 'சரிபார்ப்பு OTP குறியீட்டைப் பெற உங்கள் பதிவு செய்யப்பட்ட மின்னஞ்சல் முகவரியை உள்ளிடவும்.',
      'send_otp': 'சரிபார்ப்புக் குறியீட்டை அனுப்பு',
      'enter_otp': 'சரிபார்ப்புக் குறியீட்டை உள்ளிடவும்',
      'resend_otp': 'மீண்டும் குறியீட்டை அனுப்பு',
      'verify_otp': 'சரிபார்த்து தொடரவும்',
      'new_password': 'புதிய கடவுச்சொல்',
      'confirm_password': 'புதிய கடவுச்சொல்லை உறுதிப்படுத்துக',
      'reset_password': 'கடவுச்சொல்லை மீட்டமை',
      'back_to_sign_in': 'மீண்டும் உள்நுழைவுக்குச் செல்',
      'password_reset_success': 'கடவுச்சொல் வெற்றிகரமாக மீட்டமைக்கப்பட்டது!',
    },
  };

  String translate(String key, {String? fallback}) {
    final langCode = locale.languageCode;
    if (_localizedValues.containsKey(langCode) &&
        _localizedValues[langCode]!.containsKey(key)) {
      return _localizedValues[langCode]![key]!;
    }
    // Fallback to English
    if (_localizedValues['en']!.containsKey(key)) {
      return _localizedValues['en']![key]!;
    }
    return fallback ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ta'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationExtension on BuildContext {
  String tr(String key, {String? fallback}) {
    return AppLocalizations.of(this).translate(key, fallback: fallback);
  }
}
